<?php
/**
 * Created by PhpStorm.
 * User: m_toshpolatov
 * Date: 04.05.2018
 * Time: 10:44
 */

namespace app\widgets;


use yii\base\Widget;

class Footer extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('footer');
    }
}