<?php
/**
 * Created by PhpStorm.
 * User: m_toshpolatov
 * Date: 03.05.2018
 * Time: 11:44
 */

namespace app\widgets;


//use yii\\Widget;

use yii\base\Widget;

class Header extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('header');
    }
}