<?php
/**
 * Created by PhpStorm.
 * User: m_toshpolatov
 * Date: 03.05.2018
 * Time: 12:35
 */

namespace app\widgets;


use yii\base\Widget;

class Navbar extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('navbar');
    }

}